name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: build
        run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh
      - name: upload repository
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Linting:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true
      - name: linting
        uses: super-linter/super-linter/slim@v7 
        env:
          default_branch: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
